# 应用系统设置
[setting]
    logpath = "./logs"
    assest=""
    domain=""

# HTTP Server
[server]
	Address     = ":8199"
	ServerAgent = "myapp"

# 鉴权器设置
[tokenizer]
    loginPath   = "/login"
    logoutPath  = "/logout"
    # 启用全局拦截
    globalMiddleware = false
    # 这里是按照前缀拦截，拦截/user /user/list /user/add ...
    authPaths = []
    # 不拦截路径  /user/info,/system/user/info,/system/user,
    authExcludePaths = []

# Logger.
[logger]
    Path        = "./logs"
    Level       = "all"
    Stdout      = true

# Database.
[database]
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true
